releaseVersion: "UPDATECLI_CHART_VERSION"
semverinc: "UPDATECLI_SEMVERINC_UPDATE"
prerelease_suffix: "UPDATECLI_PRERELEASE_SUFFIX"
github:
  owner: "UPDATECLI_GITHUB_OWNER"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main"
  author: "Kubewarden bot"
  email: "cncf-kubewarden-maintainers@lists.cncf.io"
  user: "UPDATECLI_GITHUB_OWNER"
ociArtifacts:
  - image: ghcr.io/rancher/kuberlr-kubectl
    file: "charts/kubewarden-controller/values.yaml"
    key: "$.preDeleteJob.image.tag"
  - image: ghcr.io/kubewarden/policies/allow-privilege-escalation-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.allowPrivilegeEscalationPolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/host-namespaces-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.hostNamespacePolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/pod-privileged
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.podPrivilegedPolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/user-group-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.userGroupPolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/hostpaths-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.hostPathsPolicy.module.tag"
  - image: ghcr.io/kubewarden/policies/capabilities-psp
    file: "charts/kubewarden-defaults/values.yaml"
    key: "$.recommendedPolicies.capabilitiesPolicy.module.tag"
